### ISSUE TITLE
jekyll-pjax as a plugin?

### ISSUE THREAD

**Issue by n0wa11** [snaptortoise/jekyll-pjax#1]
Forget me if I am asking for something that is obvious.

Is there a way to run jekyll-pjax as a plugin for a jekyll hosting service like github ?

**Comment by georgemandis** [comment]
Not in the current incarnation. It would make a lot more sense that way. I threw this together pretty quickly before even looking into extending Jekyll.

It seems like it wouldn't be too hard to make a Generator that can do what my shell script is doing:

https://github.com/mojombo/jekyll/wiki/Plugins
